/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://y7le5a7wsvgani5qyvygfvwwg4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-w5yxpef44vgmbjqk7gavuvsimu",
    "aws_cognito_identity_pool_id": "us-east-2:b17799d9-a2ba-4736-9fe1-8e86cc2164d2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_e2jftMIi3",
    "aws_user_pools_web_client_id": "2a1dm4e6tptbhn7plhddkgg375",
    "oauth": {},
    "aws_cognito_login_mechanism": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    }
};


export default awsmobile;
